### ISSUE TITLE
Update contribution guidelines

### ISSUE THREAD

**Issue by sergeychernyshev** [iamakulov/awesome-webpack-perf#1]
Looks like [contribution guidelines](https://github.com/iamakulov/awesome-webpack-perf/blob/master/contributing.md) are a boilerplate, worth updating to clarify these:
Ensure your pull request adheres to the following guidelines:

> Make sure you take care of this
> * And this as well
> * And don't forget to check this
> * Thank you for your suggestions!

**Comment by iamakulov** [comment]
Oh damn, I missed that :) Thanks!
